version: '2'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: showman-api
    ports:
      - "5600:5600"
  webserver:
    image: nginx
    ports:
     - "80:8080"
    environment:
      NGINX_PORT=8080
